services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - DATA_DIR=/var/lib/localstack/data
      - PERSISTENCE=1
      - S3_PERSISTENCE=true
    volumes:
      - "./localstack-data:/var/lib/localstack/data"
      - "/var/run/docker.sock:/var/run/docker.sock"